In [16]:
import torch
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import numpy as np
from typing import Iterable, Tuple, Optional, Sequence, List, cast

In [17]:
# c2sのinfercodeのパーサテストコード
f = open('./data/infercode_c2s/test.c2s', 'r')
line = f.readline()
print(torch.Tensor(list(map(float,line.split("$$$")[2].split()))))
f.close()

tensor([ 0.2941,  1.1512,  0.1124, -0.4419,  0.2879, -0.4404, -0.8262, -0.4621,
        -0.4150,  0.0096, -0.5062, -0.6790,  0.6812, -0.1245, -0.2393,  0.2284,
        -0.1782,  0.9162,  0.3460,  1.4301,  0.5267, -0.4174,  0.0961, -0.6303,
         0.8158, -0.2165, -0.4829,  0.0957, -0.1219, -0.5756, -0.2096, -0.4959,
         0.0449, -0.4007, -0.1113, -0.2367,  0.4156, -0.3550, -0.6485, -0.6527,
        -0.4079, -0.1450, -0.2712, -0.0875,  2.1945,  0.2252, -0.4514,  1.8457,
        -0.5800,  0.8468,  0.3674,  3.0399,  0.5012, -0.4735, -0.0507, -0.1290,
         0.1455, -0.3554, -0.1573, -0.1794,  0.5438,  0.0187,  0.3505, -0.2027,
        -0.3633,  0.0124, -0.2332, -0.4520, -0.3507, -0.7522, -0.1207, -0.4349,
        -0.3126,  2.0307,  0.9060, -0.9791,  2.0949, -0.6425, -0.0045,  0.0709,
         1.9226,  0.2616, -0.3097, -0.3484, -0.2460, -0.5335, -0.3401,  1.8577,
         0.0319,  0.5101, -0.0797,  0.7346, -0.3400,  0.0463,  1.1056, -0.3614,
         0.7061,  1.3698, -0.2771, -0.69

In [18]:
infer_vec = torch.Tensor(list(map(float,line.split("$$$")[2].split())))

In [19]:
li = [infer_vec, infer_vec, infer_vec]

In [44]:
def transpose(list_of_lists: List[List[int]]) -> List[List[int]]: # 次元数がバグっているのはここら変だと思われる
    return [cast(List[int], it) for it in zip(*list_of_lists)]
result = transpose(li)

In [45]:
np.shape(result)

(100, 3)

In [46]:
result[0]

(tensor(0.2941), tensor(0.2941), tensor(0.2941))

In [24]:
class SimpleCustomBatch:
    def __init__(self, data):
        transposed_data = list(zip(*data))
        self.inp = torch.stack(transposed_data[0], 0)
        self.tgt = torch.stack(transposed_data[1], 0)


def collate_wrapper(batch):
    return SimpleCustomBatch(batch) # dataを受け取ってinstanceを返す。（カスタムデータ型のサポートを追加しているってわけ

inps = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
tgts = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
print(inps, tgts)
dataset = TensorDataset(inps, tgts)

loader = DataLoader(dataset, batch_size=2, collate_fn=collate_wrapper,)

for batch_ndx, sample in enumerate(loader):
    print(sample.inp)
    print(sample.tgt)

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]]) tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]])
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])
tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])
tensor([[20., 21., 22., 23., 24.],

In [27]:
from dataclasses import dataclass
@dataclass
class LabeledPathContext:
    infer_vec: torch.Tensor # infer_vec infercodeのベクトル値になる


NameError: name 'List' is not defined

In [1]:
def test(*input, **kwags):
    print(kwags)
    print(input)

In [3]:
test(1,kwags=(1,1,1,1))

{'kwags': (1, 1, 1, 1)}
(1,)


In [15]:
t1 = torch.zeros((1,3))
t1 = torch.tile(t1,(3,1))
print(t1.shape)
print(t1)
t2 = torch.zeros((2,5))

torch.Size([3, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
torch.cat((t1,t2),dim=1)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])